name: BananaGL CI

on:  
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Setup Node.js"
      uses: "actions/setup-node@v1"
      with:
        node-version: 18
    - name: Install dependencies
      run: |
        npm i
    - name: Build library
      run: |
        npm run build
